### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jpnoe** [jaouahbi/OMScrollableChart#1]

**Comment by jaouahbi** [comment]
Hi, no idea, the project is working. Just copy the OMScrollableChart directory into your project, that's all. Be aware that it is still in development, although there are several apps that are using it, it still has work to do.
cya.

Installation

> To use OMScrollableChart you must include manually all swift files located inside theOMScrollableChartdirectory directly in your project.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
